.eslintrc.js, README.md, demo/index.html, docs/api.md, docs/index.html, package-lock.json, package.json, src/auro-icon.js, src/style.scss, test/auro-icon.test.js
**Fixes:** # (issue, if applicable)
While working on `auro-button`, `auro-menu`, and `auro-dropdown`, I noticed that I was writing a lot of code to handle icons, statically and dynamically. An `auro-icon` component started to make sense to simplify how we consume our icons, but still enable individuals to consume them directly.
**By submitting this Pull Request, I confirm that my contribution is made under the …
=> auro-icon: initial build

package-lock.json, src/auro-icon.js
**Fixes:** #2, #3 
Switched from using the icon package for all the icons to the CDN.
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the …
=> fix: update icons to use CDN

README.md, demo/index.html, demo/sass/style.scss, docs/api.md, package-lock.json, src/auro-icon.js, src/style.scss, test/auro-icon.test.js
BREAKING CHANGE: This update requires a breaking change as the API for
applying custom color and size has been changed.
**Fixes:** https://github.com/AlaskaAirlines/auro-icon/issues/7
This update address the need submitted by #7, as well as address additional concerns about custom color and size management. 
See http://auro-21.surge.sh/ for demo …
=> BREAKING CHANGE: support for Alaska logos by prop

.gitignore, .npmignore, demo/alaska.html, demo/alaska.md, demo/alert.js, demo/demo.md, demo/index.html, demo/sass/style.scss, package-lock.json, package.json, scripts/prepForBuild.js, src/alaskaStyle.scss, src/baseIcon.js, src/iconStyle.scss, src/style.scss
**Fixes:** #16 
This PR addresses some general updates to include upgrading the demo docs to the new markdown format. 
=> Documents and demo upgrade

demo/demo.md, docs/api.md, package-lock.json, src/auro-icon.js, src/iconStyle.scss, test/auro-icon.test.js
This PR adds the new `label` support attribute. See screenshot. 
=> auro-icon: add label option

package-lock.json, src/auro-alaska.js, src/auro-icon.js, src/baseIcon.js
Fixes #27
Defaults boolean properties to false.
=> fix: default boolean properties to false

docs/api.md, package-lock.json, src/auro-icon.js
**Fixes:** #24
Makes the existing `uri` attribute public. This is done to allow for changing from the default use of unpkg when it goes down.
**Thank you for your …
=> fix(uri): make uri attribute public #24

demo/demo.md, demo/index.html, index.js, rollup.config.js, src/auro-icon.js
**Addresses:** #60 
- introduces the ability to extend the `AuroIcon` class and register the web component to a custom name (e.g `hf-auro-icon`)
**Thank you for your …
=> feat(customization): allow for custom component name registration and class extension

.npmignore
Updates `.npmignore` to include necc javascript files in `./src/`
**Fixes:** #74 
Updates `.npmignore` to include necc javascript files in `./src/`
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is …
=> fix(resources): update .npmignore

.npmignore, README.md, rollup.config.mjs
**Fixes:** #79
The scope of this update addresses the misconfiguration of the rollup file when creating bundled versions of the element. 
This update also addresses a performance issue with the size of the npm package. 
BEFORE
AFTER
_Pull Requests will be evaluated by their quality of update and …
=> Correct bundle file reference 

.gitignore, .npmignore, package-lock.json, package.json, packageScripts/postinstall.mjs
**Fixes:** #81 , #82 
- Bump Chalk version and all dependencies file
- Update NPM and Git Ignores File
=> Update Chalk Version, NPM and Git Ignores

.github/ISSUE_TEMPLATE/bug_report.yml
Changes to be committed:
modified:   .github/ISSUE_TEMPLATE/bug_report.yml
**Fixes:** #86 
Updates issue template to reference correct npm package
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is …
=> docs(issues): update template ro reference current npm #86

package.json
Fix branch name used for semantic release
=> fix(release): fix branch name for release

demo/alaska.md
=> perf(docs): restore alaska.md file

rollup.config.mjs
**Resolves:** #105
Add auro-alaska.js to the bundler script
=> fix(bundle): add auro-alaska.js to the bundler #105

src/auro-icon.js
**Resolves:** #107
Add `svg` part to the template.
=> feat(part): add CSS part for styling the SVG file

src/iconStyle.scss
**Resolves:** #109
Add the --auro-size-lg overwrite back into the customSize styles.
=> perf(svg): restore 100% overwrite on --auro-size-lg

.github/settings.yml, .github/workflows/testPublish.yml, package.json
**Resolves:** https://github.com/orgs/AlaskaAirlines/discussions/556
This update addresses updates to support BETA released code. 
Once this code is merged into MASTER, we can then create the BETA branch to be used for subsequent BETA releases. 
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the …
=> Update main to support BETA deployments 

docs/upstream.md, package.json
Fixes the config files that referred to the `main` branch. They now correctly refer to `master` branch.
=> build: update config for master branch name

src/auro-icon.js
**Resolves:** # (issue, if applicable)
Reincorporate the class map for the `label` attribute
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter …
=> Reinsert Classmap

package-lock.json, package.json
Moves Auro Library into `dependencies` from `devDependencies` to avoid installation issues, as originally reported in [#573](https://github.com/AlaskaAirlines/WC-Generator/issues/573).
**Resolves:** #140 
- Moved to `dependencies` within `package.json`
- Regenerated `package.lock`
- Verified `build` and `test` ran successfully
**Thank you for your …
=> fix: moves auro library to dependencies #140

src/auro-icon.js
=> fix: restore a11y label behavior for screenreader support
